name:         dart_template
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Default files for a new Dart repository
homepage:     https://github.com/bergwerf/dart-template
environment:
  sdk:        '>=2.2.0 <3.0.0'
